# Generated by Django 3.2.13 on 2022-09-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
