# Generated by Django 3.2.13 on 2022-09-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='status',
            field=models.IntegerField(choices=[(1, 'Eaten'), (2, 'ejected'), (3, 'fridge')], null=True),
        ),
        migrations.AddField(
            model_name='fridge',
            name='status_date',
            field=models.DateTimeField(null=True),
        ),
    ]
